name: Run Hello-world from py script
on: push

jobs:
  Hello:
    runs-on: ubuntu-latest

    steps:
    -  name: Clone repo
       uses: actions/setup-python@v4
       with:
         python-version: '3.10'

    - name: Run a py script
      run: python hello.py
